//
//Tessellationcontrolshader.
//

//SetGLSLversion.Minimumversionthatsupports
tessellationis4.0.
#version400
//Specifynumbersofverticesout.
layout(vertices=4)out;

//Getsinvertexpositionfromthevertexshader.
invec4vPosition[];

//Sends vertex position out to the tessellation evaluationsshader.
outvec4tcPosition[];
uniform float tessellationLevel;
uniform float scaleXY;
uniform float scaleZ;
uniform vec3 cameraPosition;

//UniformtessellationMapandnormalMap.
26uniformsampler2DtessellationMap;
uniformsampler2DnormalMap;
28
//GetID.
30#defineIDglInvocationID
32//
//NormalFromTexturetakesinthecolourvaluefromnormal
mapandsubtract0.5,
34//sincethenormalMapzerostartson0,5,thenwegetthe
valuesfrom−0,5to0,5.
//Totheendwenormalizethevector.
36//
vec3NormalFromTexture(vec3normal)
38{
normal.x=normal.x−0.5;
40normal.y=normal.y−0.5;
normal.z=normal.z−0.5;
42normal=normalize(normal);
returnnormal;
44};
46//
//DistanceFactor
48//
floatDistanceFactor(floatfactor)
59
50{
intlimit=50;
52
if(factor>limit)
54{
factor=0;
56}
else
58{
factor=(50−factor)/10;
60}
returnfactor;
62};
64//
//vertexstructcontainsnormalanddistancetoavertex
fromcameraPosition.
66//
structvertex
68{
vec3vertexNormal;
70floatdistance;
};
72
//
74//normalTessFactor
//
60
76floatnormalTessFactor(vertex[6]array)
{
78//calculatetheanglesbetweenoppositecorners.
floattestangle=acos(dot(array[0].vertexNormal,array
[3].vertexNormal));
80floattestangle90=acos(dot(array[2].vertexNormal,
array[1].vertexNormal));
floattestangle2=acos(dot(array[0].vertexNormal,array
[5].vertexNormal));
82floattestangle902=acos(dot(array[1].vertexNormal,
array[4].vertexNormal));
84
floatfactor=0;
86
if(testangle>0.90||testangle90>0.90||testangle2>
0.90||testangle902>0.90)//usesradians
88{
return(testangle+testangle90+testangle2+
testangle902);
90}
return0;
92
};
94
//
96//Main.
61
//
98voidmain()
{
100//Passesthroughthevertexposition.
tcPosition[ID]=vPosition[ID];
102
//TestthatIDiszero.
104if(ID==0)
{
106
//
108//Tessellationbasedonnormals.
//
110
//Declarevertexstructforeachsideofthepatch.
112vertex[6]abvertices;
vertex[6]advertices;
114vertex[6]dcvertices;
vertex[6]bcvertices;

124//Vectorstomakeparallelpatchedgevectorsto
comparenormals.
vec2left=vec2(vPosition[0].xy−vPosition[1].xy);
126vec2right=vec2(vPosition[1].xy−vPosition[0].xy);
vec2up=vec2(vPosition[1].xy−vPosition[2].xy);
128vec2down=vec2(vPosition[2].xy−vPosition[1].xy);
130//abVector.
//Setnormalanddistancetothetwoverticesinthe
abVector.
132abvertices[0].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[0].xy)/scaleXY).xyz);
abvertices[0].distance=distance((vPosition[0].xy),
cameraPosition.xy);
134abvertices[1].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[1].xy)/scaleXY).xyz);
abvertices[1].distance=distance((vPosition[1].xy),
cameraPosition.xy);
136
//Setnormalanddistancetothetwovertices(inthe
abVector)addedtheleftvector.
138abvertices[2].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[0].xy+left)/scaleXY).xyz);
abvertices[2].distance=distance((vPosition[0].xy+
left),cameraPosition.xy);
63
140abvertices[3].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[1].xy+left)/scaleXY).xyz);
abvertices[3].distance=distance((vPosition[1].xy+
left),cameraPosition.xy);
142
//Setnormalanddistancetothetwovertices(inthe
abVector)addedtherightvector.
144abvertices[4].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[0].xy+right)/scaleXY).xyz);
abvertices[4].distance=distance((vPosition[0].xy+
right),cameraPosition.xy);
146abvertices[5].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[1].xy+right)/scaleXY).xyz);
abvertices[5].distance=distance((vPosition[1].xy+
right),cameraPosition.xy);
148
150//adVector
//Setnormalanddistancetothetwoverticesinthe
adVector.
152advertices[0].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[0].xy)/scaleXY).xyz);
advertices[0].distance=distance((vPosition[0].xy),
cameraPosition.xy);
154advertices[1].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[3].xy)/scaleXY).xyz);
64
advertices[1].distance=distance((vPosition[3].xy),
cameraPosition.xy);
156
//Setnormalanddistancetothetwovertices(inthe
adVector)addedthedownvector.
158advertices[2].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[0].xy+down)/scaleXY).xyz);
advertices[2].distance=distance((vPosition[0].xy+
down),cameraPosition.xy);
160advertices[3].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[3].xy+down)/scaleXY).xyz);
advertices[3].distance=distance((vPosition[3].xy+
down),cameraPosition.xy);
162
//Setnormalanddistancetothetwovertices(inthe
adVector)addedtheupvector.
164advertices[4].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[0].xy+up)/scaleXY).xyz);
advertices[4].distance=distance((vPosition[0].xy+up
),cameraPosition.xy);
166advertices[5].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[3].xy+up)/scaleXY).xyz);
advertices[5].distance=distance((vPosition[3].xy+up)
,cameraPosition.xy);
168
65
170//dcVector.DothesametodcVectorasabVector
becausetheyareparallel.
dcvertices[0].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[3].xy)/scaleXY).xyz);
172dcvertices[0].distance=distance((vPosition[3].xy),
cameraPosition.xy);
dcvertices[1].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[2].xy)/scaleXY).xyz);
174dcvertices[1].distance=distance((vPosition[2].xy),
cameraPosition.xy);
176dcvertices[2].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[3].xy+left)/scaleXY).xyz);
dcvertices[2].distance=distance((vPosition[3].xy+
left),cameraPosition.xy);
178dcvertices[3].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[2].xy+left)/scaleXY).xyz);
dcvertices[3].distance=distance((vPosition[2].xy+
left),cameraPosition.xy);
180
dcvertices[4].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[3].xy+right)/scaleXY).xyz);
182dcvertices[4].distance=distance((vPosition[3].xy+
right),cameraPosition.xy);
dcvertices[5].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[2].xy+right)/scaleXY).xyz);
66
184dcvertices[5].distance=distance((vPosition[2].xy+
right),cameraPosition.xy);
186
//bcVector.DothesametobcVectorasadVector
becausetheyareparallel.
188bcvertices[0].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[1].xy)/scaleXY).xyz);
bcvertices[0].distance=distance((vPosition[1].xy),
cameraPosition.xy);
190bcvertices[1].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[2].xy)/scaleXY).xyz);
bcvertices[1].distance=distance((vPosition[2].xy),
cameraPosition.xy);
192
bcvertices[2].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[1].xy+down)/scaleXY).xyz);
194bcvertices[2].distance=distance((vPosition[1].xy+
down),cameraPosition.xy);
bcvertices[3].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[2].xy+down)/scaleXY).xyz);
196bcvertices[3].distance=distance((vPosition[2].xy+
down),cameraPosition.xy);
198bcvertices[4].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[1].xy+up)/scaleXY).xyz);
67
bcvertices[4].distance=distance((vPosition[1].xy+up
),cameraPosition.xy);
200bcvertices[5].vertexNormal=NormalFromTexture(texture(
normalMap,(vPosition[2].xy+up)/scaleXY).xyz);
bcvertices[5].distance=distance((vPosition[2].xy+up)
,cameraPosition.xy);
202
//SendthearraystothenormalTessFactor.
204floatabNormalTessellation=normalTessFactor(
abvertices);
floatadNormalTessellation=normalTessFactor(
advertices);
206floatdcNormalTessellation=normalTessFactor(
dcvertices);
floatbcNormalTessellation=normalTessFactor(
bcvertices);
208
//Calculatetheaveragetotheinnertessellation.
210floatinnerNormalTessellation=(abNormalTessellation
+adNormalTessellation+dcNormalTessellation+
bcNormalTessellation)/4;
212//
//Distance
214//
216//calculatethepositiontotheedgesofthepatch.
68
//Usethecoordinatefromtheterrain.
218vec3abMidPos=vec3(vPosition[0].xyz+((vPosition[1].
xyz−vPosition[0].xyz)/2));
vec3adMidPos=vec3(vPosition[0].xyz+((vPosition[3].
xyz−vPosition[0].xyz)/2));
220vec3dcMidPos=vec3(vPosition[3].xyz+((vPosition[2].
xyz−vPosition[3].xyz)/2));
vec3bcMidPos=vec3(vPosition[1].xyz+((vPosition[2].
xyz−vPosition[1].xyz)/2));
222
//Gettessellationfactorbysendingitto
DistanceFactor.
224floatabDistanceTessellation=DistanceFactor(distance(
abMidPos,cameraPosition.xyz));
floatadDistanceTessellation=DistanceFactor(distance(
adMidPos,cameraPosition.xyz));
226floatdcDistanceTessellation=DistanceFactor(distance(
dcMidPos,cameraPosition.xyz));
floatbcDistanceTessellation=DistanceFactor(distance(
bcMidPos,cameraPosition.xyz));
228
//Calculatetheaveragetotheinnertessellation.
230floatinnerDistanceTessellation=(
abDistanceTessellation+adDistanceTessellation+
dcDistanceTessellation+bcDistanceTessellation)/4;
232//
69
//TessellationMap
234//
236//Thesecoordinatesisscaledtobeusedonthe
texture.
vec2abMidTexPos=vec2((vPosition[0].xy+((vPosition
[1].xy−vPosition[0].xy)/2))/scaleXY);
238vec2adMidTexPos=vec2((vPosition[0].xy+((vPosition
[3].xy−vPosition[0].xy)/2))/scaleXY);
vec2dcMidTexPos=vec2((vPosition[3].xy+((vPosition
[2].xy−vPosition[3].xy)/2))/scaleXY);
240vec2bcMidTexPos=vec2((vPosition[1].xy+((vPosition
[2].xy−vPosition[1].xy)/2))/scaleXY);
242floatabTextureTessellation=texture(tessellationMap,
abMidTexPos).r;
floatadTextureTessellation=texture(tessellationMap,
adMidTexPos).r;
244floatdcTextureTessellation=texture(tessellationMap,
dcMidTexPos).r;
floatbcTextureTessellation=texture(tessellationMap,
bcMidTexPos).r;
246
//Calculatetheaveragetotheinnertessellation.
248floatinnerTextureTessellation=(abTextureTessellation
+adTextureTessellation+dcTextureTessellation+
bcTextureTessellation)/4;
70
250
//Tessellationwithallthefactors.
252
floatnormalTessellationWeight=5;
254floattextureTessellationWeight=5;
floatdistanceTessellationWeight=5;
256floatconstantTessellationWeight=1;
258glTessLevelInner[0]=1+((
constantTessellationWeight+innerNormalTessellation
*normalTessellationWeight+
innerTextureTessellation*textureTessellationWeight
+innerDistanceTessellation*
distanceTessellationWeight)/(
constantTessellationWeight+
normalTessellationWeight+textureTessellationWeight
+distanceTessellationWeight))*tessellationLevel;
glTessLevelInner[1]=1+((
constantTessellationWeight+innerNormalTessellation
*normalTessellationWeight+
innerTextureTessellation*textureTessellationWeight
+innerDistanceTessellation*
distanceTessellationWeight)/(
constantTessellationWeight+
normalTessellationWeight+textureTessellationWeight
+distanceTessellationWeight))*tessellationLevel;
71
260
glTessLevelOuter[0]=1+((constantTessellationWeight
+abNormalTessellation*normalTessellationWeight+
abTextureTessellation*textureTessellationWeight+
abDistanceTessellation*distanceTessellationWeight
)/(constantTessellationWeight+
normalTessellationWeight+textureTessellationWeight
+distanceTessellationWeight))*tessellationLevel;
262glTessLevelOuter[1]=1+((constantTessellationWeight
+adNormalTessellation*normalTessellationWeight+
adTextureTessellation*textureTessellationWeight+
adDistanceTessellation*distanceTessellationWeight
)/(constantTessellationWeight+
normalTessellationWeight+textureTessellationWeight
+distanceTessellationWeight))*tessellationLevel;
glTessLevelOuter[2]=1+((constantTessellationWeight
+dcNormalTessellation*normalTessellationWeight+
dcTextureTessellation*textureTessellationWeight+
dcDistanceTessellation*distanceTessellationWeight
)/(constantTessellationWeight+
normalTessellationWeight+textureTessellationWeight
+distanceTessellationWeight))*tessellationLevel;
264glTessLevelOuter[3]=1+((constantTessellationWeight
+bcNormalTessellation*normalTessellationWeight+
bcTextureTessellation*textureTessellationWeight+
bcDistanceTessellation*distanceTessellationWeight
)/(constantTessellationWeight+
72
normalTessellationWeight+textureTessellationWeight
+distanceTessellationWeight))*tessellationLevel;
}
}